# Generated by Django 4.2.15 on 2024-08-23 04:19

from django.db import migrations, models

def create_initial_recipes(apps, schema_editor):
    Recipe = apps.get_model('recipes', 'Recipe')
    
    recipes = [
        {"name": "Chicken Curry", "description": "A delicious chicken curry made with spices and yogurt.", "ingredients": "Chicken, Yogurt, Spices, Onions, Tomatoes", "tags": "Indian, Spicy"},
        {"name": "Sushi", "description": "Fresh sushi rolls with rice, seaweed, and fish.", "ingredients": "Rice, Seaweed, Fish, Vegetables", "tags": "Japanese, Seafood"},
        {"name": "Tacos", "description": "Mexican tacos with beef, lettuce, cheese, and salsa.", "ingredients": "Beef, Lettuce, Cheese, Salsa, Tortillas", "tags": "Mexican, Savory"},
        {"name": "Pancakes", "description": "Fluffy pancakes served with maple syrup and butter.", "ingredients": "Flour, Eggs, Milk, Maple Syrup, Butter", "tags": "American, Breakfast"},
        {"name": "Spaghetti Bolognese", "description": "Classic Italian spaghetti with a rich meat sauce.", "ingredients": "Spaghetti, Ground Beef, Tomatoes, Onions, Garlic", "tags": "Italian, Savory"},
        {"name": "Falafel", "description": "Crispy falafel balls made from chickpeas and spices.", "ingredients": "Chickpeas, Garlic, Cumin, Coriander, Parsley", "tags": "Middle Eastern, Vegan"},
        {"name": "Butter Chicken", "description": "Creamy and rich butter chicken with aromatic spices.", "ingredients": "Chicken, Butter, Cream, Tomatoes, Spices", "tags": "Indian, Mild"},
        {"name": "Beef Stroganoff", "description": "Tender beef in a creamy mushroom sauce.", "ingredients": "Beef, Mushrooms, Onions, Sour Cream, Mustard", "tags": "Russian, Savory"},
        {"name": "Pad Thai", "description": "Stir-fried noodles with shrimp, tofu, and peanuts.", "ingredients": "Rice Noodles, Shrimp, Tofu, Peanuts, Lime", "tags": "Thai, Sweet"},
        {"name": "Greek Salad", "description": "A fresh salad with cucumbers, tomatoes, olives, and feta cheese.", "ingredients": "Cucumbers, Tomatoes, Olives, Feta Cheese, Red Onion", "tags": "Greek, Healthy"},
        {"name": "Chicken Alfredo", "description": "Creamy Alfredo pasta with grilled chicken.", "ingredients": "Pasta, Chicken, Cream, Parmesan Cheese, Garlic", "tags": "Italian, Comfort"},
        {"name": "Vegetable Stir Fry", "description": "A colorful mix of vegetables stir-fried with soy sauce.", "ingredients": "Bell Peppers, Broccoli, Carrots, Soy Sauce, Garlic", "tags": "Asian, Vegan"},
        {"name": "Clam Chowder", "description": "Rich and creamy clam chowder with potatoes and clams.", "ingredients": "Clams, Potatoes, Cream, Celery, Onions", "tags": "American, Seafood"},
        {"name": "Quiche Lorraine", "description": "Savory quiche with bacon, cheese, and a custard filling.", "ingredients": "Bacon, Cheese, Eggs, Cream, Pie Crust", "tags": "French, Breakfast"},
        {"name": "Jambalaya", "description": "A flavorful Creole rice dish with shrimp, sausage, and chicken.", "ingredients": "Rice, Shrimp, Sausage, Chicken, Bell Peppers", "tags": "Creole, Spicy"},
        {"name": "Mushroom Risotto", "description": "Creamy risotto with mushrooms and Parmesan cheese.", "ingredients": "Arborio Rice, Mushrooms, Parmesan Cheese, Chicken Broth, White Wine", "tags": "Italian, Comfort"},
        {"name": "Chili Con Carne", "description": "Hearty beef chili with beans and spices.", "ingredients": "Ground Beef, Beans, Tomatoes, Chili Powder, Onions", "tags": "Mexican, Spicy"},
        {"name": "Lentil Soup", "description": "Nourishing soup made with lentils, vegetables, and spices.", "ingredients": "Lentils, Carrots, Celery, Tomatoes, Spices", "tags": "Vegan, Healthy"},
        {"name": "Banh Mi", "description": "Vietnamese sandwich with pork, pickled vegetables, and cilantro.", "ingredients": "Pork, Baguette, Pickled Carrots, Cilantro, Cucumber", "tags": "Vietnamese, Savory"},
        {"name": "Peking Duck", "description": "Crispy duck served with hoisin sauce and pancakes.", "ingredients": "Duck, Hoisin Sauce, Pancakes, Cucumber, Scallions", "tags": "Chinese, Savory"},
        {"name": "Panna Cotta", "description": "Italian dessert with a creamy vanilla custard.", "ingredients": "Cream, Sugar, Vanilla, Gelatin, Berries", "tags": "Italian, Dessert"},
    ]
    
    for recipe in recipes:
        Recipe.objects.create(
            name=recipe['name'],
            description=recipe['description'],
            ingredients=recipe['ingredients'],
            tags=recipe['tags']
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('tags', models.CharField(max_length=200)),
            ],
        ),
        migrations.RunPython(create_initial_recipes),
    ]
